In [7]:
import numpy as np
import pandas as pd

dataset = pd.read_csv("50_Startups.csv")
inputs = dataset.iloc[:, :-1].values
output = dataset.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
inputs[:, 3] = label_encoder.fit_transform(inputs[:, 3])

Because we more than 2 states, we will have to apply OneHotEncoder

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

column_transformer = ColumnTransformer([("State", OneHotEncoder(), [3])], remainder="passthrough")
inputs = column_transformer.fit_transform(inputs)

As introducing more variables can cause a dummy trap (multiple intercepts) we remove one attribute to reduce colinearity

In [27]:
inputs = inputs[:, 1:]

In [20]:
from sklearn.model_selection import train_test_split

input_train, input_test, \
output_train, output_test = train_test_split(inputs, output)

In [21]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(input_train, output_train)

LinearRegression()

In [22]:
predicted_output = regressor.predict(input_test)

In [32]:
import statsmodels.api as sm

inputs = np.append(arr=np.ones((50, 1)), values=inputs.astype(int), axis=1)
print(inputs)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Apply OLS (Ordinary Least Squares) regression model  
The summary for this OLS model will provide us with `p values` that we can use to eliminate attributes that are not needed

In [33]:
regressor_ols = sm.OLS(endog=output, exog=inputs).fit()
print(regressor_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                 -0.007
Method:                 Least Squares   F-statistic:                    0.6575
Date:                Fri, 09 Dec 2022   Prob (F-statistic):              0.421
Time:                        20:30:46   Log-Likelihood:                -600.31
No. Observations:                  50   AIC:                             1205.
Df Residuals:                      48   BIC:                             1208.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.959e+04   3370.649     11.746      0.0

c:\Python39\lib\site-packages\statsmodels\regression\linear_model.py:1934: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt(eigvals[0]/eigvals[-1])


In [34]:
inputs = inputs[:, [0, 1, 3]]
regressor_ols = sm.OLS(endog=output, exog=inputs).fit()
print(regressor_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Fri, 09 Dec 2022   Prob (F-statistic):                nan
Time:                        20:31:06   Log-Likelihood:                -600.65
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      49   BIC:                             1205.
Df Model:                           0                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.734e+04   1900.052     19.651      0.0

c:\Python39\lib\site-packages\statsmodels\regression\linear_model.py:1934: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt(eigvals[0]/eigvals[-1])
